let prices = [
  { name: "minecraft:melon_block", price: 5 },
  { name: "minecraft:pumpkin", price: 50 },
  { name: "minecraft:wheat", price: 30 },
  { name: "minecraft:carrot", price: 10 },
  { name: "minecraft:potato", price: 10 },
  { name: "minecraft:sugar_cane", price: 15 },
  { name: "minecraft:cod", price: 10 },
  { name: "minecraft:salmon", price: 10 },
  { name: "minecraft:cooked_cod", price: 20 },
  { name: "minecraft:cooked_salmon", price: 20 },
  { name: "minecraft:pufferfish", price: 10 },
  { name: "minecraft:tropical_fish", price: 10 },
  { name: "minecraft:nautilus_shell", price: 15 },
  { name: "minecraft:leather", price: 15 },
  { name: "minecraft:coal", price: 15 },
  { name: "minecraft:lapis_lazuli", price: 25 },
  { name: "minecraft:iron_ingot", price: 40 },
  { name: "minecraft:gold_ingot", price: 75 },
  { name: "minecraft:diamond", price: 150 },
  { name: "minecraft:netherite_ingot", price: 400 },
  { name: "minecraft:quartz", price: 15 },
  { name: "minecraft:redstone", price: 15 },
  { name: "minecraft:emerald", price: 100 },
  { name: "minecraft:amethyst_shard", price: 30 },
  { name: "minecraft:glowstone_dust", price: 15 },
  { name: "minecraft:obsidian", price: 50 },
  { name: "minecraft:blaze_rod", price: 40 },
  { name: "minecraft:ghast_tear", price: 150 },
  { name: "minecraft:shulker_shell", price: 200 },
  { name: "minecraft:nether_star", price: 1000 },
  { name: "minecraft:phantom_membrane", price: 25 },
  { name: "minecraft:slime_ball", price: 15 },
  { name: "minecraft:honey_bottle", price: 20 },
  { name: "minecraft:iron_nugget", price: 5 },
  { name: "minecraft:gold_nugget", price: 5 },
  { name: "minecraft:beetroot", price: 8 },
  { name: "minecraft:apple", price: 15 },
  { name: "minecraft:golden_carrot", price: 50 },
  { name: "minecraft:egg", price: 5 },
  { name: "minecraft:feather", price: 5 },
  { name: "minecraft:bone", price: 10 },
  { name: "minecraft:string", price: 5 },
  { name: "minecraft:copper_ingot", price: 25 },
  { name: "minecraft:raw_iron", price: 20 },
  { name: "minecraft:raw_gold", price: 35 },
  { name: "minecraft:raw_copper", price: 15 },
  { name: "minecraft:flint", price: 5 },
  { name: "minecraft:clay_ball", price: 5 },
  { name: "minecraft:rotten_flesh", price: 2 },
  { name: "minecraft:spider_eye", price: 10 },
  { name: "minecraft:gunpowder", price: 15 },
  { name: "minecraft:ender_pearl", price: 25 },
  { name: "minecraft:bone_meal", price: 3 },
  { name: "minecraft:ink_sac", price: 8 },
  { name: "minecraft:glow_ink_sac", price: 20 },
  { name: "minecraft:oak_log", price: 5 },
  { name: "minecraft:spruce_log", price: 5 },
  { name: "minecraft:birch_log", price: 5 },
  { name: "minecraft:jungle_log", price: 5 },
  { name: "minecraft:acacia_log", price: 5 },
  { name: "minecraft:dark_oak_log", price: 5 },
  { name: "minecraft:mangrove_log", price: 5 },
  { name: "minecraft:bamboo", price: 3 },
  { name: "minecraft:sea_lantern", price: 30 },
  { name: "minecraft:prismarine_shard", price: 20 },
  { name: "minecraft:prismarine_crystals", price: 25 },
  { name: "minecraft:scute", price: 30 }
];

export { prices };

function capitalizeWords(string: string) {
  return string
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}